module.exports.commands = require('./commands')
module.exports.database = require('./database')
module.exports.ohys = require('./ohys')
module.exports.permissions = require('./permissions')
module.exports.pixiv = require('./pixiv')
module.exports.ratelimit = require('./ratelimit')
module.exports.settings = require('./settings')
module.exports.test = require('./test')
