module.exports.schemas = require('./schemas')
module.exports.createTables = require('./createTables')
module.exports.debug = require('./debug')
module.exports.knex = require('./knex')
module.exports.updateTables = require('./updateTables')
